# Generated by Django 4.1 on 2023-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=255, verbose_name='Saison du loisir')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du loisir')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse du loisir')),
            ],
        ),
    ]
