# Generated by Django 4.2.5 on 2023-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loisir',
            old_name='adresse',
            new_name='adresse_1',
        ),
    ]
