# Generated by Django 4.1 on 2023-11-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0004_alter_client_mdp_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catégorie',
            name='categorie',
            field=models.CharField(choices=[('GA', 'Gastronomie'), ('AC', 'Arts et culture'), ('NA', 'Nature et plein air'), ('BD', 'Bien être et détente'), ('ACR', 'Ateliers créatifs'), ('EC', 'En couple'), ('EF', 'En famille')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
