# Generated by Django 4.1 on 2023-11-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0006_alter_loisir_saisons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_loisir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarseilleInsiderApp.loisir')),
                ('id_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarseilleInsiderApp.pack')),
            ],
        ),
    ]
