# Generated by Django 4.1 on 2023-11-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0007_contient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achetepack',
            name='prix_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarseilleInsiderApp.prix'),
        ),
    ]
