# Generated by Django 4.1 on 2023-11-16 11:04

import MarseilleInsiderApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0008_alter_achetepack_prix_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achetepack',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='pack',
            name='nombre_loisirs',
            field=models.IntegerField(validators=[MarseilleInsiderApp.models.validate_nombre_format], verbose_name='Nombre'),
        ),
    ]
