# Generated by Django 4.1 on 2023-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0010_rename_name_voie_loisir_nom_voie_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='prix_pack',
            field=models.IntegerField(default=12, verbose_name='Prix du pack'),
            preserve_default=False,
        ),
    ]
