# Generated by Django 4.1 on 2023-11-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0011_pack_prix_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteloisir',
            name='prix_client',
        ),
        migrations.RemoveField(
            model_name='achetepack',
            name='prix_client',
        ),
        migrations.AddField(
            model_name='acheteloisir',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acheteloisirs_id', to='MarseilleInsiderApp.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achetepack',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achetepack_id', to='MarseilleInsiderApp.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acheteloisir',
            name='date_achat_loisir',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'achat du loisir"),
        ),
        migrations.AlterField(
            model_name='achetepack',
            name='date_achat_pack',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'achat du pack"),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MarseilleInsiderApp.client')),
            ],
        ),
    ]
