# Generated by Django 4.1 on 2023-11-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0012_remove_acheteloisir_prix_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catégorie',
            name='categorie',
            field=models.CharField(choices=[('GA', 'Gastronomie'), ('AC', 'Arts et culture'), ('NA', 'Nature et plein air'), ('BD', 'Bien être et détente'), ('ACR', 'Ateliers créatifs')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loisir',
            name='saisons',
            field=models.CharField(choices=[('ETE', 'en Été'), ('HIVER', 'en Hiver'), ('AUTOMNE', 'en Automne'), ('PRINTEMPS', 'au Printemps'), ('TA', "toute l'Année")], max_length=10, verbose_name='Saison'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
