# Generated by Django 4.1 on 2023-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarseilleInsiderApp', '0013_alter_catégorie_categorie_alter_loisir_saisons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='nom_pack',
            field=models.CharField(max_length=255, verbose_name='Nom du pack'),
        ),
    ]
